In [8]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT DISTINCT Members.firstname || ' ' || Members.surname AS member_name, Facilities.name AS court_name
FROM Members
JOIN Bookings ON Members.memid = Bookings.memid
JOIN Facilities ON Facilities.facid = Bookings.facid
WHERE Facilities.name LIKE '%Tennis Court%'
ORDER BY member_name;


        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Anne Baker', 'Tennis Court 1')
('Anne Baker', 'Tennis Court 2')
('Burton Tracy', 'Tennis Court 2')
('Burton Tracy', 'Tennis Court 1')
('Charles Owen', 'Tennis Court 1')
('Charles Owen', 'Tennis Court 2')
('Darren Smith', 'Tennis Court 2')
('David Farrell', 'Tennis Court 1')
('David Farrell', 'Tennis Court 2')
('David Jones', 'Tennis Court 2')
('David Jones', 'Tennis Court 1')
('David Pinker', 'Tennis Court 1')
('Douglas Jones', 'Tennis Court 1')
('Erica Crumpet', 'Tennis Court 1')
('Florence Bader', 'Tennis Court 2')
('Florence Bader', 'Tennis Court 1')
('GUEST GUEST', 'Tennis Court 2')
('GUEST GUEST', 'Tennis Court 1')
('Gerald Butters', 'Tennis Court 1')
('Gerald Butters', 'Tennis Court 2')
('Henrietta Rumney', 'Tennis Court 2')
('Jack Smith', 'Tennis Court 1')
('Jack Smith', 'Tennis Court 2')
('Janice Joplette', 'Tennis Court 1')
('Janice Joplette', 'Tennis Court 2')
('Jemima Farrell', 'Tennis Court 2')
('Jemima Farrell', 'Tennis Court 1')
('Joan Coplin', 'Tennis Court 1')
('John Hunt', 'Tennis Court 1')
('John Hunt', 'Tennis Court 2')
('Matthew Genting', 'Tennis Court 1')
('Millicent Purview', 'Tennis Court 2')
('Nancy Dare', 'Tennis Court 2')
('Nancy Dare', 'Tennis Court 1')
('Ponder Stibbons', 'Tennis Court 2')
('Ponder Stibbons', 'Tennis Court 1')
('Ramnaresh Sarwin', 'Tennis Court 2')
('Ramnaresh Sarwin', 'Tennis Court 1')
('Tim Boothe', 'Tennis Court 2')
('Tim Boothe', 'Tennis Court 1')
('Tim Rownam', 'Tennis Court 2')
('Tim Rownam', 'Tennis Court 1')
('Timothy Baker', 'Tennis Court 2')
('Timothy Baker', 'Tennis Court 1')
('Tracy Smith', 'Tennis Court 1')
('Tracy Smith', 'Tennis Court 2')

In [5]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT 
    m1.surname || ', ' || m1.firstname AS member_name, 
    m2.surname || ', ' || m2.firstname AS recommended_by 
FROM 
    Members AS m1 
    LEFT JOIN Members AS m2 ON m1.recommendedby = m2.memid 
ORDER BY m1.surname, m1.firstname;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader, Florence', 'Stibbons, Ponder')
('Baker, Anne', 'Stibbons, Ponder')
('Baker, Timothy', 'Farrell, Jemima')
('Boothe, Tim', 'Rownam, Tim')
('Butters, Gerald', 'Smith, Darren')
('Coplin, Joan', 'Baker, Timothy')
('Crumpet, Erica', 'Smith, Tracy')
('Dare, Nancy', 'Joplette, Janice')
('Farrell, David', None)
('Farrell, Jemima', None)
('GUEST, GUEST', None)
('Genting, Matthew', 'Butters, Gerald')
('Hunt, John', 'Purview, Millicent')
('Jones, David', 'Joplette, Janice')
('Jones, Douglas', 'Jones, David')
('Joplette, Janice', 'Smith, Darren')
('Mackenzie, Anna', 'Smith, Darren')
('Owen, Charles', 'Smith, Darren')
('Pinker, David', 'Farrell, Jemima')
('Purview, Millicent', 'Smith, Tracy')
('Rownam, Tim', None)
('Rumney, Henrietta', 'Genting, Matthew')
('Sarwin, Ramnaresh', 'Bader, Florence')
('Smith, Darren', None)
('Smith, Darren', None)
('Smith, Jack', 'Smith, Darren')
('Smith, Tracy', None)
('Stibbons, Ponder', 'Tracy, Burton')
('Tracy, Burton', None)
('Tupperware, Hyacinth', None)
('Worthington-Smyth, Henry', 'Smith, Tracy')

In [6]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT 
    Facilities.name, 
    SUM(Bookings.slots) AS member_usage 
FROM 
    Bookings 
    INNER JOIN Facilities ON Bookings.facid = Facilities.facid 
WHERE 
    Bookings.memid != 0 
GROUP BY 
    Facilities.name 
ORDER BY 
    member_usage DESC;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 1086)
('Tennis Court 1', 957)
('Massage Room 1', 884)
('Tennis Court 2', 882)
('Snooker Table', 860)
('Pool Table', 856)
('Table Tennis', 794)
('Squash Court', 418)
('Massage Room 2', 54)

In [7]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT 
    Facilities.name, 
    strftime('%m', Bookings.starttime) AS month, 
    SUM(Bookings.slots) AS member_usage 
FROM 
    Bookings 
    INNER JOIN Facilities ON Bookings.facid = Facilities.facid 
WHERE 
    Bookings.memid != 0 
GROUP BY 
    Facilities.name, month 
ORDER BY 
    month, member_usage DESC;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 1', '07', 201)
('Massage Room 1', '07', 166)
('Badminton Court', '07', 165)
('Snooker Table', '07', 140)
('Tennis Court 2', '07', 123)
('Pool Table', '07', 110)
('Table Tennis', '07', 98)
('Squash Court', '07', 50)
('Massage Room 2', '07', 8)
('Badminton Court', '08', 414)
('Tennis Court 2', '08', 345)
('Tennis Court 1', '08', 339)
('Massage Room 1', '08', 316)
('Snooker Table', '08', 316)
('Pool Table', '08', 303)
('Table Tennis', '08', 296)
('Squash Court', '08', 184)
('Massage Room 2', '08', 18)
('Badminton Court', '09', 507)
('Pool Table', '09', 443)
('Tennis Court 1', '09', 417)
('Tennis Court 2', '09', 414)
('Snooker Table', '09', 404)
('Massage Room 1', '09', 402)
('Table Tennis', '09', 400)
('Squash Court', '09', 184)
('Massage Room 2', '09', 28)